export const CONTRACT_TYPES = [
  "Temps plein",
  "CDI",
  "Intérim",
  "CDD",
  "Temps partiel",
  "Alternance",
  "Contrat d'apprentissage",
  "Indépendant / freelance",
  "Service civique",
  "Stage",
  "Statut cadre",
  "Courte durée jusqu'à 6 mois",
  "Contrat de professionnalisation",
  "Job étudiant",
  "Saisonnier",
  "Courte durée jusqu'à 3 mois",
  "Fonctionnaire",
  "Contrat renouvelable",
  "Courte durée jusqu'à 1 mois",
  "Intermittent",
  "VIE",
] as const;
